config/routes.rb
Rails.application.routes.draw do
  get 'membership/create'

  get 'membership/destroy'

  resources :trips do
    get 'join', :on => :member
    get 'unjoin', :on => :member
  end

  devise_for :users

  root 'static_page#home'
  resources :users

  namespace :api , defaults: {format: 'json'} do
    namespace :v1 do
      resources :trips, only: [:create]
    end
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  #validates :user_id, presence: true
  #validates :trip_id, presence: true
  belongs_to :user
  belongs_to :trip
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  validates_presence_of :time
  validates_presence_of :date
  validates_presence_of :source
  validates_presence_of :destination
  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates_presence_of :name
         validates_presence_of :home
         validates_presence_of :work
  has_many :trips
end

app/controllers/api/v1/trips_controller.rb
module Api
  module V1
    class TripsController < ApplicationController
      # GET /trips
      # GET /trips.json
      def index
        @trips = Trip.all
      end

      # GET /trips/new
      def new
        @trip = Trip.new
      end

      # POST /trips
      # POST /trips.json
      def create
        @trip = Trip.new(trip_params)
        if @trip.save
          render json: @trip, status: :created
        else
          render json: @trip.errors, status: :unprocessable_entity
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_trip
          @trip = Trip.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def trip_params
          params.permit(:time, :date, :source, :destination, :user_id)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :home
    devise_parameter_sanitizer.for(:sign_up) << :work
  end

end

app/controllers/membership_controller.rb
class MembershipsController < ApplicationController
  before_filter :authenticate_user!

    def create
      @membership = current_user.memberships.build(:trip_id => params[:trip_id])
      if @membership.save
        flash[:notice] = "You have joined this trip."
        redirect_to :back
      else
        flash[:error] = "Unable to join."
        redirect_to :back
      end
    end

    def destroy
      @membership = current_user.memberships.find(params[:id])
      @membership.destroy
      flash[:notice] = "You have unjoined this trip."
          redirect_to :back
    end

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /trips/new
  def new
    @trip = current_user.trips.build
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = current_user.trips.build(trip_params)
    @trip.users << current_user #User Join their own trip
    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join
    @trip = Trip.find(params[:id])
    @m = @trip.memberships.build(:user_id => current_user.id)
    respond_to do |format|
      if @m.save
        format.html { redirect_to(@trip, :notice => 'You have joined this trip.') }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { redirect_to(@trip, :notice => 'Join error.') }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  rescue ActiveRecord::RecordNotUnique
    respond_to do |format|
    format.html { redirect_to(@trip, :notice => 'You already joined this trip!') }
    format.json { render json: @trip.errors, status: :unprocessable_entity }
    end
  end

  def unjoin
    @trip = Trip.find(params[:id])
    @m = @trip.memberships.find_by!(params[:user_id => current_user.id])
    @m.destroy
    flash[:notice] = "You have unjoined this trip."
        redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:time, :date, :source, :destination)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raye7 ROR Challange</title>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <%= link_to "Raye7", root_path, id: "logo" %>
      </div>
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-9" aria-expanded="false" style="height: 1px;">
          <ul class="nav navbar-nav navbar-right">

            <li><%= link_to "Home",   root_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete ,class: "btn btn-danger", id: "logoutButton"%></li>
            <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-success", id: "loginButton"%></li>
            <% end %>

          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "container alert alert-success" %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/membership/create.html.erb
<h1>Membership#create</h1>
<p>Find me in app/views/membership/create.html.erb</p>

app/views/membership/destroy.html.erb
<h1>Membership#destroy</h1>
<p>Find me in app/views/membership/destroy.html.erb</p>

app/views/static_page/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Raye7 sample App</h1>

  <h2>
    This is the home page for the ROR challange
  </h2>

  <% if user_signed_in? %>
  <% if current_user.admin? %>
  <%= link_to "Browse Users", users_path,class: "btn btn-lg btn-success"%><br><br>
  <% end %>
  <%= link_to "Browse Trips", trips_path,class: "btn btn-lg btn-info"%><br><br>
  <% else %>
  <%= link_to "Browse Trips", trips_path,class: "btn btn-lg btn-info"%><br><br>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-lg btn-primary"%><br><br>
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-success"%>
  <% end %>

</div>

app/views/trips/_form.html.erb
<%= simple_form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :time, as: :time %>
  </div>
  <div class="field">
    <%= f.input :date, as: :date, start_year: Date.today.year,end_year: Date.today.year + 10, discard_day: false,order: [:day,:month, :year] %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h3 id="myModalLabel"><%= @trip.source %>-<%= @trip.destination %></h3>
     </div>
     <div class="modal-body">
       <p>
         <strong>Time:</strong>
         <%= @trip.time.strftime("%l:%M %p") %>
       </p>

       <p>
         <strong>Date:</strong>
         <%= @trip.date.strftime("%d/%m/%Y") %>
       </p>

       <p>
         <strong>Source:</strong>
         <%= @trip.source %>
       </p>

       <p>
         <strong>Destination:</strong>
         <%= @trip.destination %>
       </p>
     </div>
     <div class="modal-footer">
       <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
       <%= link_to "Join this trip", join_trip_path(@trip),class: "btn btn-primary"%><br><br>
     </div>
   </div>
 </div>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing Trips</h1>
<ul class="users">
  <% @trips.each do |trip| %>
    <li>
      <div class="border-form-div">
        <h3><%= trip.source %>-<%= trip.destination %></h3>
        <% if trip.users.include?(current_user) %>
        <br><%= link_to "Unjoin this trip", unjoin_trip_path(trip), class: "btn btn-default" %>
        <% else %>
        <%= link_to 'Show this trip', trip,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: "btn btn-info"}  %>
        <div id="modal-window" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
        <% end %>
        <% if trip.user == current_user || current_user.try(:admin?) %>
          <br><br><%= link_to 'Edit', edit_trip_path(trip) , class: "btn btn-warning"%>
          <%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>
<br>
<%= link_to 'New Trip', new_trip_path, class: "btn btn-success", id: "new-trip"%>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
       <h3 id="myModalLabel"><%= @trip.source %>-<%= @trip.destination %></h3>
     </div>
     <div class="modal-body">
       <p>
         <strong>Time:</strong>
         <%= @trip.time.strftime("%l:%M %p") %>
       </p>

       <p>
         <strong>Date:</strong>
         <%= @trip.date.strftime("%d/%m/%Y") %>
       </p>

       <p>
         <strong>Source:</strong>
         <%= @trip.source %>
       </p>

       <p>
         <strong>Destination:</strong>
         <%= @trip.destination %>
       </p>
     </div>
     <div class="modal-footer">
       <%= link_to 'Back', trips_path, class: "btn btn-default" %>
       <% if @trip.user == current_user || current_user.try(:admin?) %>
         <br><br><%= link_to 'Edit', edit_trip_path(@trip) , class: "btn btn-warning"%>
         <%= link_to 'Destroy', @trip, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%>
       <% end %>
     </div>
   </div>
 </div>

app/views/trips/show.js.erb
$("#modal-window").html("<%= j render ('trips/show') %>");

app/views/users/index.html.erb
<title>All users</title>

<% if current_user.admin? %>
<h1>All users</h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <div class="border-form-div">
        <h2><%= link_to user.name, user %></h2>
        <p><br>Posted: <%=user.trips.count%> Trips</p>
        <% @membership = Membership.where(user_id:user.id)%>
        <p><br>Joined: <%=@membership.count%> Trips</p>
        <p><br><%= link_to 'Settings', edit_user_registration_path %></p>
      </div>
    </li>
  <% end %>
</ul>
<% else %>
<h1>Sorry, you cannot see other users information.</h1>
<% end %>

app/views/users/show.html.erb
<title><%=@user.name%></title>
<% if @user == current_user || current_user.admin? %>
<ul class="users">
  <div class="border-form-div">
    <li>
      <%= @user.name %>
      <br><%= @user.email %>
      <br>Posted: <%=@user.trips.count%> Trips
      <% @membership = Membership.where(user_id:current_user.id)%>
      <br>Joined: <%=@membership.count%> Trips
      <br><%= link_to 'Settings', edit_user_registration_path %> | <%= link_to "Back", :back %>
    </li>
  </div>
</ul>
<% else %>
<h1>Sorry, you cannot see other users information.</h1>
<% end %>